package com.brockw.stickwar.engine
{
      public class SoundLoader
      {
             
            
            public function SoundLoader(soundManager:SoundManager)
            {
                  super();
                  soundManager.addSound("acidPoolSound",acidPoolSound,1);
                  soundManager.addSound("medusaPetrifySound",medusaPetrifySound,1);
                  soundManager.addSound("deathKnightChargeSound",deathKnightChargeSound,1);
                  soundManager.addSound("fulminateSound",fulminateSound,1);
                  soundManager.addSound("wizardPoisonSound",wizardPoisonSound,1);
                  soundManager.addSound("electricWallSound",electricWallSound,1);
                  soundManager.addSound("skeltalFistsSound",skeltalFistsSound,1);
                  soundManager.addSound("skeletalReaperSound",skeletalReaperSound,1);
                  soundManager.addSound("ninjaCloakSound",ninjaCloakSound,1);
                  soundManager.addSound("speartonHoghSound",speartonHoghSound,1);
                  soundManager.addSound("orderInGame",OrderMainLoop,1);
                  soundManager.addSound("chaosInGame",ChaosMainLoop,1);
                  soundManager.addSound("lobbyMusic",LobbyMusic,1);
                  soundManager.addSound("loginMusic",LoginMusic,1);
                  soundManager.addSound("orderDeath1",orderDeath1,10);
                  soundManager.addSound("orderDeath2",orderDeath2,10);
                  soundManager.addSound("hitOnArmour1",hitOnArmour1,10,0.3);
                  soundManager.addSound("hitOnArmour2",hitOnArmour2,10,0.3);
                  soundManager.addSound("hitOnArmour3",hitOnArmour3,10,0.3);
                  soundManager.addSound("hitOnArmour4",hitOnArmour4,10,0.3);
                  soundManager.addSound("hitOnArmour5",hitOnArmour5,10,0.3);
                  soundManager.addSound("hitOnArmour6",hitOnArmour6,10,0.3);
                  soundManager.addSound("hitOnArmour7",hitOnArmour7,10,0.3);
                  soundManager.addSound("hitOnArmour8",hitOnArmour8,10,0.3);
                  soundManager.addSound("hitOnFlesh1",hitOnFlesh1,10,0.3);
                  soundManager.addSound("hitOnFlesh2",hitOnFlesh2,10,0.3);
                  soundManager.addSound("hitOnFlesh3",hitOnFlesh3,10,0.3);
                  soundManager.addSound("hitOnFlesh4",hitOnFlesh4,10,0.3);
                  soundManager.addSound("minerHit",SwordwrathHit1,10);
                  soundManager.addSound("minerDeath",GenericDeath,10);
                  soundManager.addSound("swordwrathSwing1",SwordwrathSwing1,10,0.25);
                  soundManager.addSound("swordwrathDeath",GenericDeath,10,0.5);
                  soundManager.addSound("speartonHit1",SwordwrathHit1,10);
                  soundManager.addSound("speartonDeath",GenericDeath,10);
                  soundManager.addSound("archidonBow",SwordwrathHit1,10,0.85);
                  soundManager.addSound("archidonDeath",GenericDeath,10);
                  soundManager.addSound("ninjaSwipe1",ninjaSwipe1,10,0.5);
                  soundManager.addSound("ninjaSwipe2",ninjaSwipe2,10,0.5);
                  soundManager.addSound("ninjaSwipe3",ninjaSwipe3,10,0.5);
                  soundManager.addSound("ninjaSwipe4",ninjaSwipe4,10,0.5);
                  soundManager.addSound("launchArrow1",launchArrow1,10,0.75);
                  soundManager.addSound("launchArrow2",launchArrow2,10,0.75);
                  soundManager.addSound("launchArrow3",launchArrow3,10,0.75);
                  soundManager.addSound("launchArrow4",launchArrow4,10,0.75);
                  soundManager.addSound("StatueHit1",StatueHit1,10,0.5);
                  soundManager.addSound("StatueHit2",StatueHit2,10,0.5);
                  soundManager.addSound("StatueHit3",StatueHit3,10,0.5);
                  soundManager.addSound("StatueHit4",StatueHit4,10,0.5);
                  soundManager.addSound("StatueHit5",StatueHit5,10,0.5);
                  soundManager.addSound("electricWall",electricWallSpellSound,10);
                  soundManager.addSound("mediumExplosion1",mediumExplosion1,10);
                  soundManager.addSound("mediumExplosion2",mediumExplosion2,10);
                  soundManager.addSound("mediumExplosion3",mediumExplosion3,10);
                  soundManager.addSound("voiceTutorial1",voiceTutorial1,1);
                  soundManager.addSound("voiceTutorial2",voiceTutorial2,1);
                  soundManager.addSound("voiceTutorial3",voiceTutorial3,1);
                  soundManager.addSound("voiceTutorial4",voiceTutorial4,1);
                  soundManager.addSound("voiceTutorial5",voiceTutorial5,1);
                  soundManager.addSound("voiceTutorial6",voiceTutorial6,1);
                  soundManager.addSound("voiceTutorial7",voiceTutorial7,1);
                  soundManager.addSound("voiceTutorial8",voiceTutorial8,1);
                  soundManager.addSound("voiceTutorial9",voiceTutorial9,1);
                  soundManager.addSound("voiceTutorial10",voiceTutorial10,1);
                  soundManager.addSound("voiceTutorial11",voiceTutorial11,1);
                  soundManager.addSound("voiceTutorial12",voiceTutorial12,1);
                  soundManager.addSound("voiceTutorial13",voiceTutorial13,1);
                  soundManager.addSound("voiceTutorial14",voiceTutorial14,1);
                  soundManager.addSound("voiceTutorial15",voiceTutorial15,1);
                  soundManager.addSound("voiceTutorial16",voiceTutorial16,1);
                  soundManager.addSound("voiceTutorial17",voiceTutorial17,1);
                  soundManager.addSound("voiceTutorial18",voiceTutorial18,1);
                  soundManager.addSound("voiceTutorial19",voiceTutorial19,1);
                  soundManager.addSound("voiceTutorial20",voiceTutorial20,1);
                  soundManager.addSound("voiceTutorial21",voiceTutorial21,1);
                  soundManager.addSound("voiceTutorial22",voiceTutorial22,1);
                  soundManager.addSound("MedusaVoiceOverLevel5",MedusaVoiceOverLevel5,1);
                  soundManager.addSound("wizardVoiceOver1",wizardVoiceOver1,1);
                  soundManager.addSound("wizardVoiceOver2",wizardVoiceOver2,1);
                  soundManager.addSound("wizardVoiceOver3",wizardVoiceOver3,1);
                  soundManager.addSound("wizardVoiceOver4",wizardVoiceOver4,1);
                  soundManager.addSound("medusaVoice1",medusaVoice1,1);
                  soundManager.addSound("medusaVoice2",medusaVoice2,1);
                  soundManager.addSound("medusaVoice3",medusaVoice3,1);
                  soundManager.addSound("youMustAllDie",youMustAllDie,1);
                  soundManager.addSound("clickButton",clickButton,1);
                  soundManager.addSound("newEmpirePoints",newEmpirePointsSound,1);
                  soundManager.addSound("tutorialGood1",tutorialGood1,1);
                  soundManager.addSound("tutorialGood2",tutorialGood2,1);
                  soundManager.addSound("tutorialGood3",tutorialGood3,1);
                  soundManager.addSound("tutorialGood4",tutorialGood4,1);
            }
      }
}
